let myResume={
    "basics": {
      "name": "MANIKANDAN K",
      "email": "manikandank7507@gamil.com",
      "phone": 9842436756,
      "degree": "MBA",
      "location": {
        "address": "No:15,Appai naidu street neelikonampalayam singanallur",
        "postalCode": 641033,
        "city": "Coimbatore",
        "state": "Tamilnadu",
        "country": "India"
      },
      "profiles": [
        {
          
          "github":"https://github.com/manimaddy77"
        }
      ]
    },
    "work": [
      {
        "company": "HSBC",
        "position": "KYC ANALYST",
        "startDate": "2022 -05-27",
        "endDate": "2022-11-31",
        "summary": "i am a kyc analyst maintaining lot of records and updating client details and  handling various task and gaining lots of experience",
      },
    ],
    "education": [
      {
        "institution": "SRI RAMAKRISHNA COLLEGE OF ENGINEERING AND TECHNOLOGY",
        "department": "MBA",
        "studyType": "fulltime",
        "batch start year": 2020,
        "batch end year": 2022,
        "gpa": 8.5,
      }
    ],
    "skills": [
      {
        "name": "HTML,javascript",
        "level": "beginer",
        "project": [
          "students attendance management system website"
        ]
      }
    ],
    "languages": [
      {
        "language": "Tamil,Enlish",
      }
    ],
    "interests": [
      {
        "name": "script writter,youtuber,",
      }
    ]
  }
  console.log(myResume);
  